### ISSUE TITLE
大佬大佬有SM2对字符串加密解密的例子吗

### ISSUE THREAD

**Issue by Adriaticzzz** [lpilp/phpsm2sm3sm4#1]
找了好多资料都没有php的，官方手册也没个例子，根本看不懂哇。。大佬救救孩子吧！
需要一个用公钥将明文信息加密，然后使用私钥解密成明文的例子，不胜感激

**Comment by lpilp** [comment]
还真没有现成的，可以考虑其他语言（readme上有相关的链接），或者git上有相关的C，C++的实现，你编译成PHP的扩展来使用方便些

**Comment by Adriaticzzz** [comment]
看了看openssl在PHP的API，发现SM2只在openssl_get_curve_names()里面，openssl_get_cipher_methods()里面并没有SM2，有相关的doc说明SM2的curve怎么用吗，

**Comment by lpilp** [comment]
$config = array(
     "private_key_type" => OPENSSL_KEYTYPE_EC,
    "curve_name" => 'SM2',
);
$config['config'] ='/usr/local/php/openssl/openssl.cnf';
$privkey = openssl_pkey_new($config);        
openssl_pkey_export($privkey, $publickey, null ,$config);
用PHP自带的可以生成 公私钥，  要求PHP编译进来的是 openssl1.1.1,  sm2,sm3,sm4是在1.1.1后才加入进去的，
使用了openssl1.1.1的PHP 版本， print_r(openssl_get_curve_names());最后一个就是SM2

**Comment by lpilp** [comment]
如果你是用 windows开发，使用最新版本的xampp套件的话，是 php7.4 + openssl1.1.1g,  可以直接用，苹果的话，就得升级openssl1.1.1重编译了

**Comment by lpilp** [comment]
最新版的添加了sm2的非对称加密算法了，使用查看：tsm2_encrypt.php
