### ISSUE TITLE
报错 public key format error

### ISSUE THREAD

**Issue by loving-irene** [lpilp/phpsm2sm3sm4#10]
我使用 sm2 生成了一对公私秘钥，然后用公钥加密，报错 public key format error

我看源码要求秘钥的长度必须是128位和130位，其他的都不对

**Comment by loving-irene** [comment]
> 

公私钥是银行生成了之后直接给的，别人也不知道，反正就是用现成的方法生成（java）的。直接给到我的有182字节这么长

**Comment by lpilp** [comment]
是base64的那种的吗？ 那个签名的函数里有 使用outkey的的方式，把这个写成一个.pem文件就可以了，写成这种方式，64个字节一行
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEyqo4GGHqDU6XIBpDCzEfi7Z2EpUz
mU/s46pJioQkd7tNYAb3Em2JJJRFMK4l6WPlGze3zC66NaRZuyBagjDiVQ==
-----END PUBLIC KEY-----
```
如果你想取到那种128字节的明文公钥的话，最简单的就是如果是base64就 substr(bin2hex(base64_decode($str)),-128),  本来就是16进制的那种，就直接取最后的128个应该就是了，如果取130位话，应该前面是04开头，如果不是04开头的话，就可能不是这种方式，不过大概率是这种的，银行一般用的是java且用的是就是这种的，

**Comment by loving-irene** [comment]
> 

感谢！使用文本导入的方式解决了。

这里大致说明一下，方便其他的朋友。
银行给到的公钥是HEX处理过后的（长度有182字节），加密数据以及签名值，要求使用SM2进行签名。
step1:
将HEX字符串处理，得到PEM格式，保存起来备用 [处理工具](https://the-x.cn/zh-cn/cryptography/Sm2.aspx)
step2:
调用 verifySignOutKey 即可

**Comment by lpilp** [comment]
嗯，那他们给的就是标准的sm2公钥，取明文的话使用最后的128位就行了，这个会简单点，这个asn1编码解开后是：
```
array(
    array (
          'oid1', //  对应为： ecPublicKey
          ‘oid2’, // 对应为： sm2
    ),
    array(
        '\x00',
       '04xxxxxxxxxxxxxxxxxxxxxxxx',// 04 + 128位16进度公钥明文
    ) 
)
```
