### ISSUE TITLE
sm2公钥加密后，java能解密出来吗？大佬救救孩子吧

### ISSUE THREAD

**Issue by xiaochao23** [lpilp/phpsm2sm3sm4#11]

**Comment by lpilp** [comment]
应该是没有问题的吧，我试过python, js的，同一个 msg, 同样的key, 算出来的字符串是一样的，可能是你的用法不对，你可以给个例子，我看看，你的加密串，测试用的公私钥等（不太方便的话，你的代码就用我的test中的那个公私钥），还有你的加解密中出现的问题

**Comment by xiaochao23** [comment]
我这边是对接接口,对方只给我提供了公钥,还有用java写的加密过程,我是看不明白java,java的加密代码片段如下
![270e1139fe64b69fc580500a2c10791](https://user-images.githubusercontent.com/8531536/159641911-1cafbad6-494e-410f-b218-3c68eefb8667.png)

**Comment by lpilp** [comment]
他就是sm2的非对称加密，返回值是base64编码的，你用我给的例子就行，修改下公钥,我这返回的是16进制的，java给的是base64, 你再将转换下就行了，base64_encode(hex2bin($m2EncryptData)) ，例子原码见 test/tsm2_encrypt.php, 
`require_once '../vendor/autoload.php';
use Rtgm\sm\RtSm2;
$sm2 = new RtSm2();
$publicKey = '043d9d4cc71a285af936b36880fd4d6155c22957cd2c84ea313469065207fb951b9ef1db79d69af8886e91e833da1ebc6bfdde86e70f52923d6e042eaa147624c7'; // 公钥

$document = '6220123455553';
// sm2的非对称加解密，不建议加密太长的字符串
$m2EncryptData = $sm2 ->doEncrypt($document, $publicKey);
echo ("加密后: ".$m2EncryptData);`

**Comment by xiaochao23** [comment]
搜得斯奈,我试一下,谢谢啊

**Comment by lpilp** [comment]
觉得好使，给个赞吧 ^_^

**Comment by xiaochao23** [comment]
``

**Comment by xiaochao23** [comment]
我加星了,谢谢大佬
