### ISSUE TITLE
https://github.com/wzhih/guomi 中的 tsm2.php，调用$sm2->doSign异常

### ISSUE THREAD

**Issue by 592398305** [lpilp/phpsm2sm3sm4#14]
代码块：
$sm2 = new RtSm2('base64');
$privateKey = 'aaaaaaaaaaa';
$sign = $sm2->doSign( $document, $privateKey, $userId);

报错：

gmp_init(): Unable to convert variable to GMP - string is not an integer

**Comment by 592398305** [comment]
gmp_init 函数 第一个参数是一个dobule值类型，案例中输入的是privatekey 是一个字符串。是不是错了？

**Comment by 592398305** [comment]
php版本是 5.6.31

**Comment by lpilp** [comment]
gmp_init(int|string $num, int $base = 0): [GMP](http://php.p2hp.com/manual/zh/class.gmp.php)
init就是将16进制的字符串转成大数的，参数是没问题的，
还有这个key是有密码对，不是乱写一个就行的，那个5.6的项目是wzhih 童鞋 fork后自己修改的，有什么问题可以直接在那个项目下提问题，5.6下的代码我没有测试过

**Comment by lpilp** [comment]
gmp_init('aaaaaaaa', 16), 光这个函数是没有问题的，你自己测试的时候是不是没有加那个16

**Comment by lpilp** [comment]
PHP 5.6.40 (cli)  试了下centos7下这个版本，没有报错，不知道你的是什么环境
