### ISSUE TITLE
请问是否支持Sm2WithSm3加密?

### ISSUE THREAD

**Issue by billsix123** [lpilp/phpsm2sm3sm4#16]
请问是否支持Sm2WithSm3加密?

**Comment by lpilp** [comment]
你是指sm2withsm3的hash吧， sm2的签名的hash使用的就是sm2withsm3,
/src/sm/RtSm2.php  的 301行中 做的hash就是sm2withsm3 
'''
    protected function _doS3Hash( $document, $pubKeyX, $pubKeyY, $generator, $userId ) {
        $hasher = new Sm2WithSm3();
        $hash = $hasher->getSm3Hash( $document, $pubKeyX, $pubKeyY, $generator, $userId );
        return  gmp_init( Hex2ByteBuf::ByteArrayToHexString( $hash ), 16 );
    }
'''

**Comment by billsix123** [comment]
不是的 , 是签名就采用SM2withSM3签名算法，签名方式为PKCS#1裸签名 , 同时验签也是用的SM2withSM3

**Comment by lpilp** [comment]
这个就不太知道了，你试下，我觉得就是 我说的那个，裸签名就是 $hash = $hasher->getSm3Hash( $document, $pubKeyX, $pubKeyY, $generator, $userId ); 这个值, bin2hex($hash)

**Comment by lpilp** [comment]
或者你 给个例子，我试下是哪种签名

**Comment by billsix123** [comment]
感谢感谢 , 已经实现了->doSign就可以直接签

**Comment by lpilp** [comment]
哦，看来是在在命名上理解差异的问题 ^_^
