### ISSUE TITLE
SM2加密密文的排列方式的C1.C2.C3和C1.C3.C2区别

### ISSUE THREAD

**Issue by wangshantao** [lpilp/phpsm2sm3sm4#18]
给我示例的java的代码排序方式是C1.C2.C3，而且加密完的密文会以04开头。调整PHP代码成C1.C2.C3并在前面加上04，java就能进行相应的解密。是我这边java的代码写的不标准吗？还是sm2有多种实现方式？

**Comment by lpilp** [comment]
sm2的标准是 c1,c3,c2 ,其他的椭圆算法倒是c1c2c3的，这个问题不大，根据对方的需求更改顺序就可 
是否已04开头，一般未强求，根据自己的项目需求添加就可，

**Comment by wangshantao** [comment]
学到了，感谢
