### ISSUE TITLE
Uncaught Mdanter\Ecc\Exception\UnsupportedCurveException: Invalid data: unsupported generator.

### ISSUE THREAD

**Issue by PoemRainPR** [lpilp/phpsm2sm3sm4#2]
Uncaught Mdanter\Ecc\Exception\UnsupportedCurveException: Invalid data: unsupported generator.
\phpsm\phpsm2sm3sm4\vendor\mdanter\ecc\src\Serializer\Util\CurveOidMapper.php:141
这是什么意思？求大佬解救

**Comment by lpilp** [comment]
vendor/mdanter/ecc/src/Serializer/Util/CurveOidMapper.php  修改这个文件的第28行，将oid改成：‘1.1.0.0.101’， 或是任意的，
我也觉得奇怪，oid='1.2.156.10197.1.301' , 这个才是它真正的oid, 用这个就报错了，等有空再看看，先解决你的问题， 如果只是做签名，验签名的话，这个oid倒没用到，在生成证书的话，那是得用到的，每个oid都有国际标准的，不能乱写

**Comment by PoemRainPR** [comment]
想再问下大佬支持sm2withsm3加密吗？

**Comment by lpilp** [comment]
sm2的签名，验签就要用到sm2withsm3的啊， MySm2中的第 211行 ， 
 $hasher = new Sm2WithSm3();        $hash = $hasher->getSm3Hash( $document, $pubKeyX, $pubKeyY, $generator, $userId );这个哈稀就是sm2withsm3,  你是不是看到有一个104 行的sha256,  这个可用可不用，这个是签名的时候要有一个生成中间随机数的算法，124行那有注释，为什么要这个随机数，随机数固定时，同一段字符生成的签名是固定的

**Comment by PoemRainPR** [comment]
由于对这个国密不太了解，感谢大佬的不厌其烦的回答
也就是说我直接调用mySm2中的doSign方法进行加签，verifySign方法进行验签就可以了对吗

**Comment by lpilp** [comment]
> 
> 
> 由于对这个国密不太了解，感谢大佬的不厌其烦的回答
> 也就是说我直接调用mySm2中的doSign方法进行加签，verifySign方法进行验签就可以了对吗

对，直接用就行了（要求PHP7 + 打开php-gmp模块）， 生成的数据可以与其他语言的互签互认的，其他语言的测试可以看readme里提到的其他地址，我都测试过了的，都可以用

**Comment by PoemRainPR** [comment]
加签的时候是没有问题的，验签的时候总是提示格式不对，我看了第三方给的公钥是124位的，但是代码中是128位和130位。请问下您知道124位的是怎么回事吗

**Comment by lpilp** [comment]
128与130的区别是前面的标志位 ‘04’，如果是04开头，然后代码就知道使用的软件的密码， 一般软件会判定位数，130位的就把04去掉，124的好像是那个硬件用的密码，有一个转换的，以前查到过相关的资料，我得找找

**Comment by PoemRainPR** [comment]
好的，麻烦你找下，辛苦了。能否留下联系方式加下好友呢

**Comment by PoemRainPR** [comment]
> 128与130的区别是前面的标志位 ‘04’，如果是04开头，然后代码就知道使用的软件的密码， 一般软件会判定位数，130位的就把04去掉，124的那个不知道是怎么弄的，问下第三方，正常不是64字节的公钥，你怎么62字节

是的呀，我在网上也搜不到有124，我也特意问了第三方，他们的技术支持说就是124位的，没有错，然后用java的代码也能进行验签，这就不知道为啥了。如果实在找不到方法，我这边也只能调用java的方法进行验签了。

**Comment by lpilp** [comment]
你用的java是BC库的代码吗？还是哪个开源的，给个地址，我看下，应该是有一个算法解成128位的

**Comment by PoemRainPR** [comment]
> 你用的java是BC库的代码吗？还是哪个开源的，给个地址，我看下，应该是有一个算法解成128位的

15151548963这是我微信，我把源码发你，我自己看不懂，是让java同事写接口调用的
