### ISSUE TITLE
composer安装不了 使用的框架是laravel

### ISSUE THREAD

**Issue by lijiangit** [lpilp/phpsm2sm3sm4#21]
Problem 1
    - lpilp/guomi[v1.0.0, ..., v1.0.2] require mdanter/ecc 0.5.2 -> satisfiable by mdanter/ecc[v0.5.2].
    - lpilp/guomi 1.0.3 requires mdanter/ecc ^1.0 -> satisfiable by mdanter/ecc[v1.0.0].
    - mdanter/ecc v0.5.2 requires php ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
    - mdanter/ecc v1.0.0 requires ext-gmp * -> it is missing from your system. Install or enable PHP's gmp extension.
    - Root composer.json requires lpilp/guomi ^1.0 -> satisfiable by lpilp/guomi[v1.0.0, v1.0.1, v1.0.2, 1.0.3].

To enable extensions, verify that they are enabled in your .ini files:
    - D:\phpstudy_pro\Extensions\php\php8.0.3nts\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by lijiangit** [comment]
使用的php版本是8.0.3

**Comment by lpilp** [comment]
PHP 8 好像缺省没有gmp组件， 你php -m 看下有没有这个组件，没有的放在，安装下就可以了，
我用php8.1试过

**Comment by lijiangit** [comment]
@lpilp  谢谢 明白了

**Comment by lijiangit** [comment]
在对接招行的时候 私钥格式是NBtl7WnuUtA2v5FaebEkU0/Jj1IodLGT6lQqwkzmd2E= 和 调用生成明文密钥生成的私钥格式"27a89f351cfc52351d416615785f2e2f4cd35ff2f96d04e291a661645bc4c2f0" 不是一样的   用招行的用户私钥签名时，报gmp的一个错误gmp_init(): Argument #1 ($num) is not an integer string， 请问这种格式的私钥怎么签名呢

**Comment by lpilp** [comment]
bin2hex(base64_decode("NBtlxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"))   base64解一下就好了，

**Comment by lijiangit** [comment]
万分感谢
