### ISSUE TITLE
哪位大佬能给个lajp可以调用的jar包啊

### ISSUE THREAD

**Issue by honghuzhi** [lpilp/phpsm2sm3sm4#24]
哪位java大佬，能帮忙把java的国密，打包成jar，可以提供 php的 lajp调用，非常感谢，实在没办法了

**Comment by lpilp** [comment]
你这是想用PHP调用java来操作？ 为啥不直接用PHP呢，现在的readme.md里增加了常见问题，有什么问题可以直接提

**Comment by honghuzhi** [comment]
> 
不是说现在php包有些sm2解不出么？和Java对接可能还是有兼容性问题，银行提供的都是Java包，就怕不兼容
而且目前生产服务器只安装了php7.3，但php包需要php7.4，目前也不方便对生产服务器升级

**Comment by lpilp** [comment]
你是指验证签名的时候吗？目前只有招行的那个有点问题，我加了一个类，按需要自己重新解析下，看readme最后一项，

**Comment by honghuzhi** [comment]
目前中行的sm2加解密能验证通过吗？

**Comment by lpilp** [comment]
你是指sm2的非对称加解密？ 一般不是只用的签名不， 加解密的话比较少人用，目前加解结果用的c1c3c2这种依靠位数才取c1, c3，c2值的确有问题，这个的确没有多试过

**Comment by honghuzhi** [comment]
是的，中行用的就是sm2非对称加密，SM3WITHSM2 和 sm2p256v1 格式

**Comment by lpilp** [comment]
sm2p256v1就是现在的这个sm2椭圆的样子， sm3whithsm2, 现在的hash也是用的这个， 至于中间的数据处理，没有java sdk的源码就不知道是怎么操作的了， 这样的话，还是用他给的sdk打包操作安全点

**Comment by honghuzhi** [comment]
问个题外话，服务器版本centos6.5 ，如果升级到支持 sm3/sm4的openssl版本，升级完成后，是否需要重新编译安装php和nginx呢？还会有别的软件受影响吗？

**Comment by lpilp** [comment]
1 手动安装openssl1.1.1以上， 2 编译安装PHP， with的openssl是用新的 然后PHP就支持了，如果你是用apache的话，倒是有个捷径， 安装linux版的最新版xampp全家桶， 你可以只使用他的PHP， 这个全家桶的PHP支持sm3, sm4。 不过如果只用sm3,sm4的话，这两个的运算还是比较快的，直接用PHP就行，编译超麻烦。 https://github.com/lizhichao/sm  用这位童鞋的，sm3用他的， sm4要修改一下下，可以用我的，我的就是从他那里修改的，添加了补齐，他的没有补齐与其他语言不通
