### ISSUE TITLE
php版本依赖，必须是7.4以上了吗？

### ISSUE THREAD

**Issue by honghuzhi** [lpilp/phpsm2sm3sm4#25]
我看readme里说大于7.2就行啊，现在怎么需要7.4以上了啊

**Comment by honghuzhi** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - lpilp/guomi 1.0.3 requires mdanter/ecc ^1.0 -> satisfiable by mdanter/ecc[v1.0.0].
    - lpilp/guomi[v1.0.0, ..., v1.0.2] require php >=7.4 -> your php version (7.3.21) does not satisfy that requirement.
    - mdanter/ecc v1.0.0 requires ext-gmp * -> it is missing from your system. Install or enable PHP's gmp extension.
    - Root composer.json requires lpilp/guomi ^1.0 -> satisfiable by lpilp/guomi[v1.0.0, v1.0.1, v1.0.2, 1.0.3].

**Comment by lpilp** [comment]
前面几个版本当时是按我本机的PHP弄的，最新版 1.0.3 就降到7.2了，强制下版本号试下

**Comment by lpilp** [comment]
我把composer上的旧版给整理了下，现在应该不会有问题了
