### ISSUE TITLE
sm2 解密失败

### ISSUE THREAD

**Issue by honghuzhi** [lpilp/phpsm2sm3sm4#27]
Curve curve(115792089210356248756420345214020892766250353991924191454421193933289684991996, 18505919022281880113072981827955639221458448578012075254857346196103069175443, 115792089210356248756420345214020892766250353991924191454421193933289684991999) does not contain point (2137854832359249130018667759494391183761873155309590729559322389203168722373, 111751830531928666539205041330488512151142167531666828532858683705993727777102)

**Comment by lpilp** [comment]
sm2 非对称加密后是 c1c3c2,  c1是计算时中间椭圆的公钥，公钥又分为两部分， px,py, 这个报错就是px, py不匹配了，py != Gpx了，原因在于，计算时中间椭圆是随机生成的，这时会有概率生成的公钥的位数（转成16进后）的短了， 而解码的时候是按128这个来截的， 这个算法上的确是有问题的，目前最优化的是 加密后的串  asn1(px,py, c3,c2)这种，就不会出现这个问题，还有就是中间椭圆不要随机，用固定的位数足的。我的1.0.4版本在加密的时候做了补足，但解密的时候的确是有问题，

**Comment by jinchun** [comment]
我这里使用这个库去解密业务方提供的加密字符串也出现类似问题了，一筹莫展中。

**Comment by lpilp** [comment]
> 我这里使用这个库去解密业务方提供的加密字符串也出现类似问题了，一筹莫展中。

你把前段一给个 150字节，我看下，是不是我上面说的问题，当时没有仔细研究这个问题，我参考下其他语言的解决方案，试下能否解决

**Comment by lpilp** [comment]
> 我这里使用这个库去解密业务方提供的加密字符串也出现类似问题了，一筹莫展中。
还有一个，就是如果加密串开头以04开头，就把04去掉，我这没有判定，你试下，因为有时候真可能会是04开头的，

**Comment by lpilp** [comment]
> Curve curve(115792089210356248756420345214020892766250353991924191454421193933289684991996, 18505919022281880113072981827955639221458448578012075254857346196103069175443, 115792089210356248756420345214020892766250353991924191454421193933289684991999) does not contain point (2137854832359249130018667759494391183761873155309590729559322389203168722373, 111751830531928666539205041330488512151142167531666828532858683705993727777102)

找到你这个问题，你的这个不是我说的那个问题，是返回的加密串中临时公钥C1前面有一个04，去掉04应该可以

**Comment by lpilp** [comment]
> 我这里使用这个库去解密业务方提供的加密字符串也出现类似问题了，一筹莫展中。

你看下是否返回的加密串中临时公钥C1前面有一个04，去掉04应该可以

**Comment by lpilp** [comment]
最新的版本应该可以解决这个问题
