### ISSUE TITLE
php7.0能支持吗？

### ISSUE THREAD

**Issue by 1997wen** [lpilp/phpsm2sm3sm4#28]

**Comment by 1997wen** [comment]
目前生产环境是7.0，能发布一个PHP >= 7.0 的版本吗

**Comment by lpilp** [comment]
你用我readme.txt里的介绍的另一个童鞋fork的 支持5.6的那个， 我的这个调用了asn1的组件要求php7.2以上

**Comment by 1997wen** [comment]
> 你用我readme.txt里的介绍的另一个童鞋fork的 支持5.6的那个， 我的这个调用了asn1的组件要求php7.2以上

不支持sm2，只支持sm3、sm4

**Comment by lpilp** [comment]
https://github.com/lpilp/sm3_sm4  那你可以用这个，把sm3, sm4从项目中提取出来了， 该项目,直接把sm3, sm4两个文件拿出来就能用了
