### ISSUE TITLE
同样的参数，java的每次签名结果都会有变化，为啥php的签名结果是不变的？

### ISSUE THREAD

**Issue by leftYxy** [lpilp/phpsm2sm3sm4#29]
参数一致：
用招行的javademo跑，打印签名，每次结果都不一样。
用php跑，结果不变的？是什么原因造成的呢

**Comment by lpilp** [comment]
```
class RtSm2 {
    protected $adapter = null;
    protected $generator = null;
    protected $userId = '1234567812345678';
    // 是否固定签名不随机，好处是同一段参数的签名固定，增大别人的猜测的难度
    protected $useDerandomizedSignatures = true;
```
你把这个参数改成false就行了，签名的时候需要生成一个中间椭圆，固定的话每次生成的是固定的，缺点就是它是固定的，优点一则生成速度更快，减少生成中间椭圆的消耗， 二则就是注释里写的，看需要了，这个随意

**Comment by leftYxy** [comment]
好的。谢谢了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月1日(周一) 中午12:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lpilp/phpsm2sm3sm4] 同样的参数，java的每次签名结果都会有变化，为啥php的签名结果是不变的？ (Issue #29)




 class RtSm2 {     protected $adapter = null;     protected $generator = null;     protected $userId = '1234567812345678';     // 是否固定签名不随机，好处是同一段参数的签名固定，增大别人的猜测的难度     protected $useDerandomizedSignatures = true;  
你把这个参数改成false就行了，签名的时候需要生成一个中间椭圆，固定的话每次生成的是固定的，缺点就是它是固定的，优点一则生成速度更快，减少生成中间椭圆的消耗， 二则就是注释里写的，看需要了，这个随意
