### ISSUE TITLE
大佬，SM4加解密能java互通吗？

### ISSUE THREAD

**Issue by weisifen** [lpilp/phpsm2sm3sm4#3]
您文档中的
java : https://github.com/ZZMarquis/gmhelper
java SM4代码中的encrypt_ECB_Padding

**Comment by lpilp** [comment]
可以的，sm4加解密比较简单，如果发现不一样，可以一步步的调试，git上下载一个java BC 库的java源码调试

**Comment by weisifen** [comment]
> 可以的，sm4加解密比较简单，如果发现不一样，可以一步步的调试，git上下载一个java BC 库的java源码调试

大佬有时间能帮忙看下吗？java代码如下，php代码应该咋调整？困扰了几天了，有偿的帮看也行[捂脸]
java代码：
/**
     * 加密
     *
     * @param data
     * @param key
     * @return
     * @throws Exception
     */
    public static String sm4Encrypt(String data, String key) throws Exception {
        byte[] encrypt = SM4Util.encrypt_ECB_Padding(ByteUtils.fromHexString(key), data.getBytes("utf-8"));
        return Base64.toBase64String(encrypt);
    }

    /**
     * 解密
     *
     * @param data
     * @param key
     * @return
     * @throws Exception
     */
    public static String sm4Decrypt(String data, String key) throws Exception {
        byte[] encrypt = SM4Util.decrypt_ECB_Padding(ByteUtils.fromHexString(key), Base64.decode(data));
        String plainData = new String(encrypt, Charset.forName("utf-8"));
        return plainData;
    }

**Comment by lpilp** [comment]
String skey = "51949f0dd1c3cf5aa948eaa4a786227c";
            String smsg = "{\"prdCode\":\"51949f0dd1c3cf5aa948eaa4a786227c\"}";
            byte[] msg = smsg.getBytes();
            byte[] key = ByteUtils.fromHexString(skey);
            byte[] cipherText = null;
            byte[] decryptedData = null;
           cipherText = SM4Util.encrypt_ECB_Padding(key, msg);
            System.out.println("SM4 ECB Padding encrypt result:\n" + ByteUtils.toHexString(cipherText));
这个算出来的是：95753f81b365bb7965ab8d5eeaa0b7aa30e17277023e517605b1d08dccb73f8f0b5ce79a949c5806d8c936eb7c6a6125 与你的那个java算出来的也不一样，你的那个base64解开是: 8fb5d3467e073ae32d8f6ec06c52ce9f9564bc1ff8b6f1a19b3aee904033bc6c344812f68341f2ebaee359b92a1018c0,也不太一样，

还有就是PHP的那个加密的方式你用错了， PHP的函数里的key 是要原始的 key, 需要 
$key_raw = "51949f0dd1c3cf5aa948eaa4a786227c";
$key = hex2bin($key_raw); 这样后，加密出来的就一样的是：95753f81b365bb7965ab8d5eeaa0b7aa30e17277023e517605b1d08dccb73f8f0b5ce79a949c5806d8c936eb7c6a6125
