### ISSUE TITLE
验签的性能是否可以优化

### ISSUE THREAD

**Issue by xfmo** [lpilp/phpsm2sm3sm4#30]
生成签名的性能看着比较差，是否可以进行优化。
还有，RtSm2.php文件中 _dosign 方法 这段代码应该是可以去掉的吧 `$publickey = $key->getPublicKey(); `看着比较耗性能。

```
protected function _dosign( $document, $key, $adapter,$generator, $userId, $algorithm = 'sha256' ) {
        $publickey = $key->getPublicKey();

        $obPoint = $key->getPublicKey()->getPoint();

        $pubKeyX = $adapter->decHex( $obPoint->getX() );
        $pubKeyY = $adapter->decHex( $obPoint->getY() );
```

**Comment by lpilp** [comment]
$publickey = $key->getPublicKey();  的确是可以去掉。至于 说优化的问题，刚开始时这也是一个工作上的一个赶进度项目，东拼西凑才勉强可用。这个也是基于通用ecc的，代码冗余量大，类有点多，性能的确比较差。得下个月估计会有点时间，弄一个简化版本的，应该性能会好一点点.

**Comment by xfmo** [comment]
嗯嗯，期待下一个性能好的的版本。
