### ISSUE TITLE
sm4 cbc 解密失败

### ISSUE THREAD

**Issue by lvyac** [lpilp/phpsm2sm3sm4#31]
密文：（base64）L1R0VmZsY0wrazVXdjJnSUNETDJybHZyc2t6WUt5QVE4U21XK0hKTXBuVXhnVUg5aVlmNWg5NEJSdU42aVkzUUMzQmxJekcycXhZc1duYzAydnQvZXc9PQ==

ErrorException in Sm4.php line 299  未定义数组下标: 2

**Comment by lpilp** [comment]
1 decrypt($data, $type = 'sm4', $iv = '', $formatInput = 'hex') ,缺省是 hex，是否把hex修改成base64,  这几个函数都用openssl系列的自带函数进行过测试，没有发现什么问题
2 你可以用 openssl_decrypt($ciphertext, "sm4", $key, $options=OPENSSL_RAW_DATA,$iv) 试下能不能解开，不知道你的密码，这我无法给你调试，缺省安装openssl系列不支持这个，可以使用 xampp组件中的php的，自动支持或是在openssl1.1.1.x下编译安装的PHP也支持

**Comment by lpilp** [comment]
对了，还有你要确定下用的是哪种，是cbc(密码还有一个向量IV), 还是ecb（没有向量），缺省的是cbc, 这个别弄混了
