### ISSUE TITLE
招行SM2解密失败

### ISSUE THREAD

**Issue by xfmo** [lpilp/phpsm2sm3sm4#33]
请教一下为什么使用招行的SM2解密不出来数据，调用doDecrypt 方法报错 PPHP Fatal error:  Uncaught Mdanter\Ecc\Exception\PointNotOnCurveException: Curve curve(115792089210356248756420345214020892766250353991924191454421193933289684991996, 18505919022281880113072981827955639221458448578012075254857346196103069175443, 115792089210356248756420345214020892766250353991924191454421193933289684991999) does not contain point (21923053050521176574017647783284950498893389114667304193717803804932173814757, 56509344826246672192550335824034926620678438138637932737988965091437702175940) in /Users/flying/.composer/vendor/mdanter/ecc/src/Primitives/Point.php:104

SM2密文如下：
042b1c1eff060f1ad922fd0af05e4c613f436f799c9c96e0de8ca15be57cef27de5287a0703fdec5404d7c08e08a89049d23267892fbfa7c925cc453f2c1ca30a643426f3068e98f4ebf945d57f12b479fb2f91e7ce683c56c8d05478e2d58b9650ee886229b5599befb29d71d802a47b7

是否可以加个qq（9***0）或者微信（Littl***Mo）

**Comment by lpilp** [comment]
最新的版本应该是做了兼容的，主要是密文的时候前面多了个04， 把04去掉就可以了，
```
/**
     * SM2 私钥解密算法, 
     *
     * @param string $document
     * @param string $privateKey  如提供的base64的，可使用 bin2hex(base64_decode($privateKey))
     * @param bool $trim 是否做04开头的去除，看业务返回
     * @return string
     */
    public function doDecrypt($encryptData,$privateKey,$trim = true)
    {
        // $encryptData = $c1.$c3.$c2
        if(substr($encryptData,0,2)=='04' && $trim){
            $encryptData = substr($encryptData,2);
        } 
        $adapter = $this->adapter;
        $generator = $this->generator;
        $this->cipher = new \Rtgm\smecc\SM2\Cipher();
```

**Comment by xfmo** [comment]
去掉04也不行，解密出来的值为空了

**Comment by lpilp** [comment]
加你了

**Comment by lpilp** [comment]
我 这要求私钥是16进制的，然后64个16进制字符，
你可以看下 test/tsm2_encrypt.php 的例子

**Comment by xfmo** [comment]
需要将招行asn1换行成C1C3C2的格式（非C1C2C3）才可解密出来。
