### ISSUE TITLE
useDerandomizedSignatures属性设置

### ISSUE THREAD

**Issue by xxren** [lpilp/phpsm2sm3sm4#34]
你好，使用中遇到如下问题：

RtSm2 类中 这个属性的作用 $useDerandomizedSignatures = true;
 
 目前测试 true时 请求招行有sign失败的概率， 改成false 反而可以通过；

**Comment by lpilp** [comment]
有错误日志的不，有利于排查，这边也测试下

**Comment by lpilp** [comment]
这边测试了几千个随机数的签名与验证没有报出什么错出来，你把test/tsm2.php, 修改下，重新生成一个密码对，循环个至少1千次以上，$documnt随机生成，看看结果，

**Comment by xxren** [comment]
你 wx 多少，我这边发你实际遇到的case～

**Comment by xxren** [comment]
你 wx 多少，我这边发你实际遇到的case～

**Comment by lpilp** [comment]
Recent007

**Comment by lpilp** [comment]
解决方案见 readme,最下面的关于招行
