### ISSUE TITLE
sm2加密出来的java好像不认

### ISSUE THREAD

**Issue by hsk-story** [lpilp/phpsm2sm3sm4#35]
https://github.com/ZZMarquis/gmhelper
java使用gmhelper解密

解密的时候直接就报错了, 有人测试成功过吗

**Comment by lpilp** [comment]
这边生成的的加密串的c1部分是前面是没有04的， 比如这边生成的是“e27c3780e7069bda7082a23a489d77...... ”, 在java里应该是encryptStr = “04e27c3780e7069bda7082a23a489d77...... ”， 前面加个04,  然后再转成 byte类型（java库里的参数是byte型），ByteUtils.fromHexString(encryptStr)  应该就可以了，

**Comment by lpilp** [comment]
这边生成的的加密串的c1部分是前面是没有04的， 比如这边生成的是“e27c3780e7069bda7082a23a489d77...... ”, 在java里应该是encryptStr = “04e27c3780e7069bda7082a23a489d77...... ”， 前面加个04,  然后再转成 byte类型（java库里的参数是byte型），ByteUtils.fromHexString(encryptStr)  应该就可以了，

**Comment by lpilp** [comment]
比如，用我的例子的公私钥生成原文为 “I_LOVE_YOU!”的加密串，如下，只要前面补个04就可以解出来
```java
String encryptStr = "04e27c3780e7069bda7082a23a489d77587ce309583ed99253f66e1d9833ed1a1d0b5ce86dc6714e9974cf258589139d7b1855e8c9fa2f2c1175ee123a95a23e9bf28d5991d14f73a65efa25c24d3cfbd7cb4f8807aa4bc6ecd5b755d6fe4e6db71f3cdfb9274cb848d422de";
            byte[] encryptByte = ByteUtils.fromHexString(encryptStr);
            byte[] decrptByte = SM2Util.decrypt(priKey, encryptByte);
            System.out.println("decrypt is : " + new String(ByteUtils.toCharArray(decrptByte)));
```

**Comment by hsk-story** [comment]
解决了! 感谢
