### ISSUE TITLE
请教关于掌上生活 Sm3WithSm2 签名问题

### ISSUE THREAD

**Issue by Millyn** [lpilp/phpsm2sm3sm4#36]
# 招行在线测试
https://open.cmbchina.com/Platform/#/test/tools/signProtocol

# 测试密钥
## Private Key
af6443adfe00684f1cc646661877db7b9cc2f85979e1f60f1f081d61a1397a8b

## Publick Key
04dc02516a229e0c19ff78e75a3943c0c877cf41f7fac1f89b921f0bf98a197b4adf180be8c30b02b8cbd13bf7a70f1a6ca626a0b63fec11c8256b5e2c925d3453

# 测试 MSG
```
cmblife://approval?aid=1234567890&clientType=h5&date=20221010111302&mid=1234567890&random=217395f3019a4613aacd5e363068a2a7&callback=javascript%3AcallbackApproval&responseType=code&scope=defaultScope&state=1234567890
```

# 尝试

我使用 测试 MSG 在掌上生活在线进行签名，然后在线验证签名是可以验证通过。

但使用本库生成出来的 sign 结果验证失败。

由于我不是很了解国密，所以做了以下相关尝试都不正确。

## 参数
```
$str = 'cmblife://approval?aid=1234567890&clientType=h5&date=20221010111302&mid=1234567890&random=217395f3019a4613aacd5e363068a2a7&callback=javascript%3AcallbackApproval&responseType=code&scope=defaultScope&state=1234567890';

$privateKey='af6443adfe00684f1cc646661877db7b9cc2f85979e1f60f1f081d61a1397a8b';
```

## 第一种，直接 SM2->Sign
```
        $privateKey = config('zssh.privateKey');
        $key = bin2hex(base64_decode($privateKey));
        $sm2 = new RtSm2('base64', false);
        $doSign = $sm2->doSign($str, $key);
        var_dump($doSign);
```

## 第二种，SM2->Sign(SM3->sign,privateKey)
```
        $sm3 = new RtSm3();
        $digest = $sm3->digest($str);

        $privateKey = config('zssh.privateKey');
        $key = bin2hex(base64_decode($privateKey));

        $sm2 = new RtSm2('base64', false);
        $doSign = $sm2->doSign($digest, $key);

        var_dump($doSign);
```

## 第三种，不对 privateKey 做任何处理
```
        $privateKey = config('zssh.privateKey');
        $sm2 = new RtSm2('base64', false);
        $doSign = $sm2->doSign($str, $privateKey);
        var_dump($doSign);
```

## 问题

我也看了 Readme 里所提到的关于招行补 0 的问题，使用 `src/util/FormatSign->format_cmbc` 过滤 Sign，比如上述代码，我把 $doSign 结果放入 format_cmbc 里执行，其结果和未 format 的base64 一致。

所以这个情况该怎么使用本库？谢谢～

**Comment by lpilp** [comment]
你测试的时候使用 test/tsm2.php, 将公私钥替换成你的，用那里面的测试就可以了，你现在的用法不对的样子
readme里的关于招行是因为招行过来的签名会有小概率多了0， 生成的签名给招行的时候也会有极小的概率招行不认，所以加了那两个函数重新format下， 正常情况format前与后是一样的，只有碰到了这个小概率的时候才会不一样，概率不到1%，你试个几千次（随机生成要签名数据），应该会碰到几次 fomat前后不一致的，

**Comment by Millyn** [comment]
> 你测试的时候使用 test/tsm2.php, 将公私钥替换成你的，用那里面的测试就可以了，你现在的用法不对的样子 readme里的关于招行是因为招行过来的签名会有小概率多了0， 生成的签名给招行的时候也会有极小的概率招行不认，所以加了那两个函数重新format下， 正常情况format前与后是一样的，只有碰到了这个小概率的时候才会不一样，概率不到1%，你试个几千次（随机生成要签名数据），应该会碰到几次 fomat前后不一致的，

感谢回复，主要原因是 doSign 的第三个参数 $userId 没有使用默认值 `1234567812345678` 所造成的问题，其他的用法是一致的。
无论 RtSm2 在初始化时是否使用中间椭圆都可以适配掌上生活。

ps: 我今天复用昨天的代码居然也可以成功，不知道是不是 composer test 时产生了 cache 导致本地代码有点混乱。

总之，问题解决了，感谢。

**Comment by lpilp** [comment]
如果用在正式环境对接招行就一定要format一下，不然业务比较多的话，就会有概率出现那个多0少0的问题，可以下载招行提供的sdk的java的源码就可以看出问题出在哪了，使用BC库原始生成的就挺好了，招行程序员小哥非得上面再封装一下，反而出了这个bug
