### ISSUE TITLE
请问现在还需要gmp扩展的支持吗？

### ISSUE THREAD

**Issue by chenzhenhua007** [lpilp/phpsm2sm3sm4#37]
如题。我看介绍里有提到，“要求PHP７，打开gmp支持”。但how to use里没说需要gmp支持。

**Comment by lpilp** [comment]
要的啊，加密什么的都是做大数运算，得开gmp扩展，这个在php5 就已经有的，缺省就安装上的样子，只是有些版本的PHP.ini里没有打开

**Comment by chenzhenhua007** [comment]
好的，thankyou
