### ISSUE TITLE
和java对接，SM2无法解密数据

### ISSUE THREAD

**Issue by chenzhenhua007** [lpilp/phpsm2sm3sm4#38]
发送过来的加密数据：BHWhrp6JQAtFQ4McVazw4TuUFDn45rncS+73A/+it1Nm1qxupMHwDvP5Hv+cohlPkrZDucF8wq/bAgygQt6Ue6O+oodLHngdK9JS/i2Si19YgX1HCzzBU8ClSU9xotkfDG/RJ/kspjg5g0HhTAG+HeKLEAklkb599sa7sR0QvA3/3EiHiLz2zTxuvrfjjTHJSDe1xlducWTKE5ZxNreH5OmP7GWRBcrdlfz2BLBDC34y6Eqqp7pkJcnlbL/QqxcUGNHNJI2R0/em4k8JQCUiWl1KrxkhwAwYs/WLrIz2C8u7EmLHZBckVcJMKBYlFU++lL6/FC4P67EiyJ/Mo/m7mGA2nicQxUJKNxwHbM6sGoIXAReLocztf+iU5Yf7UikgLA/780ciA87ZTwWOgjPzCw1hORb4UQMXopLm+sLgFDjTQ7Ro61bmBa7g49wDiTurgrTUIk9TahP+M1Q7wz309sjwdoQrZgrp4a+r0Ai/TFv+HE8ligwELl6JxG6yejRzB7UzJFGCTGIl1KaKYYdHJAyPdrtcxD+UbjYNAuRJ/qXiG+Ynuk4ysIT1vUJCsyuYgZyOzx9dUck91JnLpqI2wpTXPgoINMXSJHNwW1uMJlPFy+WWUzhBvreRLaDI2cb6ftAL/9K4vpSq1Yk5Oq0aRB6O18H4ZVwoni9mOF7t4Lo/KKpuOPWLU3XeYXJqnmZ4KQwAvC5whVDOiiX6N/XNfsVDYaN4YJ04ijyeogdjXDfV/QT+27q2/XileaqLzdcUp/LF9xN9vrK3xFZ58TV7dPUWHDQJ3CqeArsD4dU1Y4d9diA3VM+AB7Egb4kMY5lWxM92d7YkiKgzzCgDiAkDS30FsJGfgfbYQc90kUUAnQ2286d06i60Rt+7diXPakcTCyWvvrkHc9TrnGsunDtUuFV+GbNV6tmRP3im85UZ0deqQJZ8WMQUpR612mipWDACkC8lDok8sd+xv9ZyDYnAvsyAF/Lnsp/XeRPLjwBjVlr1tw/bExgLfJV6yWD9caIVLsNJl+hFNBP2/bruh+fTvexzs89NdeSXE27j4UL4YnqTu3W5vrobZXthaHJofBat95yd+XvfjgRsCxcb3DjkvFN6cIpRfk9xbGOGJhEwjnW1PIjgE5yFC7xzE4kZ29+mSsRnqkvYncCHidSz7ImYSMlT04bQBY8TtzuRC9FZCUJ5A2iSWH+AAX4XruwldKdzPV7SuTqAjPyu2W0/FLM4b6BKPer5d2jg2Ztold9lAMN/hG8M4kTjDzTAJvQOM6pug/PHmLCBiq8Qrg7d80z/UkPSmLa9JU0WqPqUlBTwvbW8hsqSBi5iVdx8foaEmkVKrhaQvGtndbQ6dqgQJDJtCMcGFGnZSzOOKARtppPf9pN8rIcYYRF2ma7Z8JRt6gbjj3ODHYOOQ44hFnpAdbWu2sFVoYNMFZVLEIDb/GvxerOqXzw26jEqb9bL1LIdLiE0fXISR01vs4txziet6xFkss3z8pD65PqkXv33TUv2ATEffA/x6MRiOC9ZidaZ0L53XyoVvfSBD6rg5k2eT9+KHffCHaGOn79rklapUXh5ejkga7zByPN8pyr/0I0sACkssHxpDfhlBNVvOEOBT9WgktpUiyYxpkEIXjL4EO6paXPE0EAbpWfwMUEyLBPhgiu0lWxAhddaSuJPUD/unt0L8tsb83tcAYTrf2Qa6K1BhzBpSF9+LH8ZLcQikT1De/hPABeEdchPhLrnUudGASX5VeyPVLBQo+z5XG+cJvMzKEYPmGbQMBDUhGQcD5L9/uh403kmD6u4IasyCjPZhHHffu4KoDJJttYlXfZmE5Au1lXaIbgRo115EWlavM04N32qTfvJgJAPawEU89n9jx9mNmvYSzOilZVZMQZ4DdjL6WOm6VYAni9JXjiGfCXjy6o6m7Uv9tc2d17dkCwsMZUfsuhRHLa6AcnamIn08LLoHtEGYGJHinvXLcCc4DD+tt5QshUxZKpSi1x3OCDuwLhOPbpUSymSHV6mfyE0T3/WoWdGQZ9ndhbABdfmwKvZxMmuq/q/hiLEGtJSwe0nSGygh5hifXb6+3KXEmwrG9Fc/Yn+FvvC7X74R+/xEspAcuJPl3eNk8WrYn/be2vOXjPyKZk5EG2W2SNQuWHmKFLxH82nfTyRPQ+LTPNtF7N+JdwjjQ+xx3LdhlJpWUshMPyMNUOC+FbWpof0K66EMQZiJpwjr1FAyVthgHsVITqZNBbzv7hWTqZb4s8SAojVknSixhnHw0khm1cnMdseZQdymrT0LfFgeKnTpOljHiE/D6oAwKviRjtPnbGS2jsYBuC+KP1msfriICV86DOA84D8YqGjkdddq2d9pLL/LBy5kHE967/lUKsExz8MR6I0Ho2DYbNe0C4XswgMsic=
私钥：7eba45f536af51377a0e7c1346d9a746348ba8581ce2957d3bdc0bdf3fb2f715
php代码：
$sm2 = new RtSm2();
$originalData = $sm2->doDecrypt(bin2hex(base64_decode($encryptData)), $privateKey);
解出来的数据为空。
感觉和issues#33问题很像
如果，第3个参数改为，false，去掉前面的04，则报错
$originalData = $sm2->doDecrypt(bin2hex(base64_decode($encryptData)), $privateKey, false);
报错如下：
"message": "Curve curve(115792089210356248756420345214020892766250353991924191454421193933289684991996, 18505919022281880113072981827955639221458448578012075254857346196103069175443, 115792089210356248756420345214020892766250353991924191454421193933289684991999) does not contain point (2017088389800493414537223642471494436295912431580677090622203970508929808211, 46515205910672524411678083181661249619220354456023358688557825284463176619131)",
    "exception": "Mdanter\\Ecc\\Exception\\PointNotOnCurveException",
    "file": "C:\\phpstudy_pro\\WWW\\www.dianzibaohan.com.cn\\dianzibaohan\\vendor\\mdanter\\ecc\\src\\Primitives\\Point.php",
    "line": 102,
    "trace": [
        {
            "file": "C:\\phpstudy_pro\\WWW\\www.dianzibaohan.com.cn\\dianzibaohan\\vendor\\lpilp\\guomi\\src\\sm\\RtSm2.php",
            "line": 156,
            "function": "__construct",
            "class": "Mdanter\\Ecc\\Primitives\\Point",
            "type": "->"
        },
        {
            "file": "C:\\phpstudy_pro\\WWW\\www.dianzibaohan.com.cn\\dianzibaohan\\app\\Http\\Controllers\\Api\\LiaoningController.php",
            "line": 968,
            "function": "doDecrypt",
            "class": "Rtgm\\sm\\RtSm2",
            "type": "->"

麻烦问一下@lpilp，如果按照issues#33的方法，怎么使用asn1换成C1C3C2。。

**Comment by lpilp** [comment]
我把你的私钥用 xxxxx隐藏了，在公共地方不要随意给私钥，通过私钥是可以算出来公钥的，

**Comment by lpilp** [comment]
```php
$m2EncryptData = bin2hex(base64_decode($str)); 加密串如果base64
// var_dump($m2EncryptData);
$c1 = substr($m2EncryptData,0,130); //前面有04，没有的话就128 相应的后面也修改成128
$c3 = substr($m2EncryptData,-64);
$c2 = substr($m2EncryptData,130,strlen($m2EncryptData)-130-64);

$m2EncryptData = $c1.$c3.$c2;
```
这样就行了，
