### ISSUE TITLE
sm2对接java无法解密

### ISSUE THREAD

**Issue by yuehuaxw** [lpilp/phpsm2sm3sm4#39]
如题：
1、java那边是c1c2c3标准
2、加密串前面存在04
3、密钥前面存在00
遇到问题：
1、如果解密是$trim=false，去除密文前面的04，则报错如下：
"Curve curve(115792089210356248756420345214020892766250353991924191454421193933289684991996, 18505919022281880113072981827955639221458448578012075254857346196103069175443, 115792089210356248756420345214020892766250353991924191454421193933289684991999) does not contain point (2220918082519640839271715907941306834420976183340709641538589670659070624315, 2317117560351423785808682426051180236027355204224107987385986039750006104008)"
2、我对c2,c3的取值顺序进行了调整，则$document的结果全是乱码
还请大佬帮忙解答一下 @lpilp

**Comment by lpilp** [comment]
是否可以把加密后的串 看一下， 不用 公钥私，只要加密后的数据

**Comment by lpilp** [comment]
$m2EncryptData = bin2hex(base64_decode($str));
// var_dump($m2EncryptData);
$c1 = substr($m2EncryptData,0,130); //前面有04，
$c3 = substr($m2EncryptData,-64);
$c2 = substr($m2EncryptData,130,strlen($m2EncryptData)-130-64);

$m2EncryptData = $c1.$c3.$c2;
你试下这个

**Comment by yuehuaxw** [comment]
感谢大佬 回头我再研究一下

**Comment by yuehuaxw** [comment]
感谢大佬 回头我再研究一下
