### ISSUE TITLE
how to use？

### ISSUE THREAD

**Issue by pope445** [lpilp/phpsm2sm3sm4#4]

**Comment by lpilp** [comment]
看src下的mysm2.php文件，对相关的签名，验签，生成公私钥的方法进行了简单封装，vendor是在phpecc的基础上加了sm2的椭圆，加入得有点生硬，当时图快就加到nist的椭圆里，这个不太对，最好是单独列出一种椭圆类型，原始的ecc的 sep, nist两种椭圆
用法就看test下的文件，那样调用就行了， 根据你自己的需要调整文件结构，
如果使用框架的话，将src下的文件放到library下，vendor文件夹与原有的（如原来没有使用vendor的第三方库，就一般放到与application平级位置就行）合并，修改autoload,将ecc加入就行，
