### ISSUE TITLE
你好大佬 我用你的验证包 和https://const.net.cn/tool/sm2/verify/  这个网站相互验签总是失败怎么回事

### ISSUE THREAD

**Issue by liweioop1** [lpilp/phpsm2sm3sm4#42]
你好大佬 我用你的验证包 和https://const.net.cn/tool/sm2/verify/  这个网站相互验签总是失败怎么回事
大佬我说的是sm2 签名和验签
我先doSing 生成了签名
因为没有R值和S值 我需要
导出R值和S值
$sm2 = new RtSm2();
$sign = $sm2->doSign($data, $key, $userid);
$signData= hex2bin($sign);
$a = \FG\ASN1\ASNObject::fromBinary($signData)->getChildren();

$rr= formatHex($a[0]->getContent());
$ss= formatHex($a[1]->getContent());
$sign = $rr. $ss;
$sign = hex2bin($sign);  //这个是R/S签名

以下是验签
$signHex = bin2hex($sign);
$r = substr($signHex, 0, 64);
$s = substr($signHex, 64, 64);

$r = gmp_init($r, 16);
$s = gmp_init($s, 16);

$signature = new Signature( $r, $s );
$serializer = new DerSignatureSerializer();
$serializedSig = $serializer->serialize($signature);
$sign = bin2hex($serializedSig) ;

$b = $sm2->verifySign($data, $sign, $publicKey, $userid);

function formatHex($dec)
{

    $hex = gmp_strval(gmp_init($dec, 10), 16);
    $len = strlen($hex);
    if ($len == 64) {
        return $hex;
    }
    if ($len < 64){
        $hex = str_pad($hex, 64, "0", STR_PAD_LEFT);
    }else {
        $hex = substr($hex, $len - 64, 64);
    }

    return $hex;
}

这样是自己是可以验证签名的  但是和别的网站却不能互签互验 
求大佬帮帮忙  解决以下到底什么原因 我都快崩溃了

**Comment by lpilp** [comment]
没有问题的啊，可能是你解开的代码，哪里写错了，你用我test/ttsm2.php的例子你试下， 我试了是没有问题的，
公钥：3D9D4CC71A285AF936B36880FD4D6155C22957CD2C84EA313469065207FB951B9EF1DB79D69AF8886E91E833DA1EBC6BFDDE86E70F52923D6E042EAA147624C7
userID: 不变，我的也是用这个缺省的
Data(*): E68891E788B1E4BDA0494C4F5645594F5521  (“我爱你ILOVEYOU!”的16进制)
R：67C8940F544FBBA6BEC2E9CC0CC86DF0D01A8C045DB5D494A34B466329244340
S：F84449C01CA96E43D534EABACA500B9969335BD914844CB3AB109FDD60D5430F

例子缺省是返回的base64的， 你修改下：$sm2 = new RtSm2('hex',true); 返回就是hex的， 还有只要你的第二个参数是 true, 我这程序对于同公钥同签名串签名出来的每次都是一样的，如需要每次不一样，将true改false， 不过用true的话，测试时比较好测试，你跑出来看 数据就和我一样了

**Comment by liweioop1** [comment]
大佬能不能先加我qq  我怕一会联系不上你了
