### ISSUE TITLE
您好，对接的是浦发的sm2

### ISSUE THREAD

**Issue by 791487145** [lpilp/phpsm2sm3sm4#43]
gmp_init(): Unable to convert variable to GMP - string is not an integer in file /Users/szh/laravel/nmydmall/vendor/lpilp/guomi/src/sm/RtSm2.php on line 170
解密的时候他的密文我得到的就是这个错误

**Comment by lpilp** [comment]
第170行： $p1 = new Point( $adapter, $generator->getCurve(), gmp_init($c1X, 16 ), gmp_init( $c1Y, 16 ) ); 
这个函数暂时是只支持 加密串是 hex的， 你这个报错说明$cx1 不是16进制数，你看下加密串是什么数，最大可能是base64的，
那在解码前需要   bin2hex(base64_decode($str)) 下

**Comment by 791487145** [comment]
是您说的问题，谢谢啦，找了好一天找不到问题

**Comment by lpilp** [comment]
这个sm2 的加解密是后来加的，没有加入相关的编码形式，刚更新了下，如果构造的时候是base64的就按base64解决
