### ISSUE TITLE
关于招行的验签

### ISSUE THREAD

**Issue by pengfugui** [lpilp/phpsm2sm3sm4#44]
你好，我现在在用这个库处理业务，也成功处理了几个项目，很有帮助，首先感谢。
然后最近我在对接招行，目前验签的部分一直失败，我的代码如下
`      $fs = new FormatSign();
        $newSign = $fs->run($badSign);
        echo $newSign."\n";
        $sm2 = new RtSm2('base64');
        $ret = $sm2->verifySign($data, $newSign, $publicKey, '1234567812345678');`

这样返回false，而用招行的demo是返回true。
如果不做FormatSign::run,直接验签则会异常。
我有看到readme中关于招行验签的说明，可能我没看懂，希望得到指点，谢谢

**Comment by lpilp** [comment]
意思是： 招行给过来的签名，要用  FormatSign::run 过滤一下， 然后再走主流程验证； 给招行签名的时候 ，先用主流程生成签名，然后将签名再用 FormatSign->format_cmbc() 格式化下，再发给招行。 你那下载下招行的demo，看下他的java的源码就可以知道是怎么回事， 他调用了BC 库的 签名函数后，又自己封装了下，但显然外包程序员没有对 asn1编码的理解出了偏差，所以出现了现在的问题，目前应该就招行会有这样的问题，其他行的没有发现

**Comment by pengfugui** [comment]
感谢回复，但是我遇到了新的问题，就是在centos7 php7.2.8,开启了gmp。用FormatSign::run 或者FormatSign->format_cmbc的话，程序会挂起，死循环了。新开一个终端ps会看到进程并且kill不掉，是否还需要其他的配置呢？

我的用法是，先rtsm2->doSign获得base64的签名值，然后再FormatSign->format_cmbc。或者是获得招行的签名值之后，先FormatSign::run处理，然后rtsm2->verifySign

**Comment by lpilp** [comment]
/test/tfsign.php  单独用这个例子替换你的数据调试下，可能是我的代码有问题，或者就是你的参数不对，参数是 base64的，或者你把你的一个签名给我 我试下， 只要签名就可以，不用密钥
