### ISSUE TITLE
请问服务器openssl版本需要多少能正常使用sm2加密解密呢？

### ISSUE THREAD

**Issue by mxm145** [lpilp/phpsm2sm3sm4#47]
目前如果服务器配套的使用的是openssl 1.1.1x， 目前到1.1.1.l(t) ，sm3，sm4都可以直接用openssl_xxx系列函数直接实现，不必大量的代码，但不支持sm2的签名，sm2的加解密

请问服务器openssl版本需要多少能正常使用sm2加密解密呢？
我服务器上的openssl是1.1.1f，加密后c#解密不了

**Comment by lpilp** [comment]
不支持sm2，只支持sm3,  sm4

**Comment by lpilp** [comment]
我这指的都是PHP的相关的openssl_xx 函数，C#的话，不熟悉，你可以看看 https://github.com/hz281529512/SecretTest 这个项目

**Comment by mxm145** [comment]
还有一点就是本项目中c1前面没有04， 视对接方的需求，看是否添加\x04

这个是在哪里添加呢？我这边是需要解密C#用SM2加密的数据，前面是有04的

**Comment by lpilp** [comment]
这个添加04是指加密给别人的时候， 看你们双方约定要不要加；解密中如果对方的加密串有04， 会将04缺省是去掉的  doDecrypt($encryptData,$privateKey,$trim = true,$model = C1C3C2)， trim参数就是去掉04,

**Comment by mxm145** [comment]
能给个联系方式吗？我这边折腾好久都没办法解密成功，想请教一下

**Comment by lpilp** [comment]
给我你的联系方式，发我邮箱  lpilp@126.com
