### ISSUE TITLE
可以再发布一个最新的版本么？

### ISSUE THREAD

**Issue by erxiao16** [lpilp/phpsm2sm3sm4#51]

**Comment by erxiao16** [comment]
我现在的运行环境时 php8.0 ，运行时，出现了两个问题，，我提交了 我修改的代码，并描述了解决的问题点。

**Comment by lpilp** [comment]
intval的问题修复， 动态属性的问题，“AllowDynamicProperties”只在8.2以后才有，在其他版本上没有，用了会报错，转而将该类中相关的动态属性先申明了

**Comment by lpilp** [comment]
版本已发 1.0.7

**Comment by lpilp** [comment]
不好意思，那个版本与其他版本有兼容性的问题，如你只使用签名的话，没有问题，有使用加解密的话，请使用1.0.8版本
