### ISSUE TITLE
1.0.7版本 不兼容 以前版本

### ISSUE THREAD

**Issue by yxqa123** [lpilp/phpsm2sm3sm4#54]
src/smecc/SM2/Hex2ByteBuf.php
```
$temp_1 = $indata / 16;
        $temp_1 = intval($indata / 16);
        if ($temp_1 < 10)
            $temp_1 = $temp_1 + 0x30;
    ..
}
```
intval 改变了 最终 temp_1 的结果。导致与 1.0.7 以前版本结果差异。
sm2 加密结果与 1.0.7以前版本不兼容，可能与其他语言的也不兼容

**Comment by lpilp** [comment]
这个没有问题，这个函数其实就是做一个 dechex（） 函数，10进制转16进制而已，项目是用别人的修改的，一些转换什么函数没有去变动，这个理论上就得加intval的，最后的chr( int assic ),需要传int值，传float值的话就取整数部分了，中间的运算也都是整数运算，不会有什么问题，你是遇到什么问题了不，我看看。
感谢关注！
PS： 正在弄不依赖其他库的版本，应该会支持 >=5.4 或是5.6  一个简化的签名验签版本，有需要请关注，大概会在6月中上

**Comment by yxqa123** [comment]
我的项目使用的 1.0.4.1  1.0.6 1.0.7

**Comment by lpilp** [comment]
看了下，的确是欠考虑了，原来的加解密缺省返回的hex, 本想支持下 base64，逻辑上有点问题，感谢反馈，一会更新

**Comment by lpilp** [comment]
这个1.0.7缺省返回的base64了，已回退了，发了1.0.8
