### ISSUE TITLE
问个问题：JAVA中的SM3WITHSM2，在这个项目中要如何调用、配置？

### ISSUE THREAD

**Issue by weishuiliang** [lpilp/phpsm2sm3sm4#58]

**Comment by lpilp** [comment]
你说的SM3WITHSM2是指sm2的签名吧，    参考 test/tsm2的例子使用 ， 在同样的密钥的情况下 与java应该是互通的，由于使用的java 项目返回的格式不同，要换成一样的格式，本项目是 的签名是  asn1(r, s)的base64 签名（decode后第一个字符是 \x30），你看下你的的java项目返回的签名是什么样式的，一般也是 asn1(r,s) 的 base64签名， 极个别返回的是 r + s 这种签名，
