### ISSUE TITLE
使用sm4-ecb提示Uncaught Exception: 秘钥长度为16位

### ISSUE THREAD

**Issue by machiming** [lpilp/phpsm2sm3sm4#64]
java那边给我的加密后的秘钥是32位的2beedbfe8361da78459235de842c8ac2加密前的key也是32位的，传入new RtSm4($key)报Uncaught Exception: 秘钥长度为16位。请完可以如何解决

**Comment by lpilp** [comment]
这个16是指字节（bin），32位的是hex 的， 32位的做一个 hex2bin就行了

**Comment by machiming** [comment]
感谢大佬的回答，是的
$client_secret = '32位的16进制字符串'
$skMd5 = md5($client_secret);
$key = hex2bin($client_secret);
这样就可以了
