### ISSUE TITLE
sm2 缺少文件

### ISSUE THREAD

**Issue by qingshang8433** [lpilp/phpsm2sm3sm4#67]
src/ecc/Sm2Signer.php  这个文件
use Mdanter\Ecc\Crypto\Signature\SignatureInterface;
use Mdanter\Ecc\Crypto\Signature\Signature;

缺少Signature

**Comment by lpilp** [comment]
项目是采用composer 的文件标准，如果是直接clone下来跑的话， 需要 composer install 下，将需要的依赖安装一下的，项目里没有存依赖文件，所以直接运行测试文件是不行的，依赖请查看package.json文件，

**Comment by qingshang8433** [comment]
不让用composer

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月04日 15:02 |
| 收件人 | lpilp/phpsm2sm3sm4 ***@***.***> |
| 抄送人 | levilog ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [lpilp/phpsm2sm3sm4] sm2 缺少文件 (Issue #67) |

项目是采用composer 的文件标准，如果是直接clone下来跑的话， 需要 composer install 下，将需要的依赖安装一下的，项目里没有存依赖文件，所以直接运行测试文件是不行的，依赖请查看package.json文件，

**Comment by lpilp** [comment]
找一台能composer的，把生成的verdor 复制过来呗，如果只用到sm2 相关的签名，加解密，倒可以用这个项目的简化版本，那个没有添加第三方依赖  https://github.com/lpilp/simplesm2

**Comment by qingshang8433** [comment]
多谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月04日 18:24 |
| 收件人 | lpilp/phpsm2sm3sm4 ***@***.***> |
| 抄送人 | levilog ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [lpilp/phpsm2sm3sm4] sm2 缺少文件 (Issue #67) |

找一台能composer的，把生成的verdor 复制过来呗，如果只用到sm2 相关的签名，加解密，倒可以用这个项目的简化版本，那个没有添加第三方依赖 https://github.com/lpilp/simplesm2
