### ISSUE TITLE
lpilp/guomi v1.0.2 requires php >=7.4 which does not match your installed version 7.2.0. 

### ISSUE THREAD

**Issue by jiangyao-zh** [lpilp/phpsm2sm3sm4#7]
是否可以支持7.2？

**Comment by lpilp** [comment]
7.2实际上问题不大，我装的7.4， 因为ecc的库做了强类型验证，有朋友在7.2的时候会验证比较严，会报异常，我的是7.4倒是不报，所以使用了7.4这个限制，应该是修改下就行，我有空时看看，在7.2下要使用，你直接下载git直接修改就可以，简单修改下就能用，现在准备要支持8， 这个ecc库在8下不太好使，也得升级

**Comment by lpilp** [comment]
更新了，我用我的php7.2没有问题，有朋友用的php7.2会报数据类型的异常，你试试
