### ISSUE TITLE
 does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by mrstocksir** [lpilp/phpsm2sm3sm4#70]
![1111](https://github.com/lpilp/phpsm2sm3sm4/assets/23026289/bac134e6-c4c6-4e39-83e3-54ac3d7df002)

**Comment by lpilp** [comment]
请忽略，这个忘记删除了

**Comment by lpilp** [comment]
可能与你的compser版本有关，我这边不会报这个，我把那个不要的文件夹删除了， 上了一个1.0.9版本，重新下载应该可以了

**Comment by woweijun123** [comment]
> 可能与你的compser版本有关，我这边不会报这个，我把那个不要的文件夹删除了， 上了一个1.0.9版本，重新下载应该可以了

![image](https://github.com/lpilp/phpsm2sm3sm4/assets/14172436/576eec11-308b-46c2-974b-39464784f7fb)

**Comment by lpilp** [comment]
刚更新到最新的稳定2.6.6也没有这个提示的样子，

**Comment by woweijun123** [comment]
> 刚更新到最新的稳定2.6.6也没有这个提示的样子，

PHP 8.2.15 
    
Composer version 2.6.6 2023-12-08 18:32:26

**Comment by woweijun123** [comment]
> 刚更新到最新的稳定2.6.6也没有这个提示的样子，

![Uploading image.png…]()

**Comment by woweijun123** [comment]
> 刚更新到最新的稳定2.6.6也没有这个提示的样子，

<img width="1282" alt="image" src="https://github.com/lpilp/phpsm2sm3sm4/assets/14172436/9edce30b-9d23-437d-be5d-56cbe1768a1d">

**Comment by lpilp** [comment]
php8 对PHP的检测做了比较严格的规范，从PHP5开始写PHP的，一些总会各种warning
