### ISSUE TITLE
请问支持php5.6吗

### ISSUE THREAD

**Issue by wzhih** [lpilp/phpsm2sm3sm4#8]
如题，老项目是php5.6的，难搞

**Comment by lpilp** [comment]
sm2的不支持呢，用到了php-ecc的第三方类库，用到了php7以后的语法，
sm3, sm4的话，倒是可以在php5.6下单独运行，单独clone下来封装使用，用composer安装不了
建议你升级到7.4 目前7的版本里最新的稳定版，php比python什么的都好，向下基本兼容，除了取消了mysql得用mysqli, 如果你使用一些框架的话，只要配置那里修改成mysqli引擎就行了，如果是手写的话，的确有点麻烦。其他基础不会有什么问题

**Comment by lpilp** [comment]
https://github.com/lizhichao/sm  只使用sm3,sm4的话，用这位童鞋的支持5.6，且支持compser安装 ， 就是sm4的 ecb,cbc算法里需要做补齐，你重新封装下就行， 项目的issue里有说这个问题的

**Comment by wzhih** [comment]
> sm2的不支持呢，用到了php-ecc的第三方类库，用到了php7以后的语法， sm3, sm4的话，倒是可以在php5.6下单独运行，单独clone下来封装使用，用composer安装不了 建议你升级到7.4 目前7的版本里最新的稳定版，php比python什么的都好，向下基本兼容，除了取消了mysql得用mysqli, 如果你使用一些框架的话，只要配置那里修改成mysqli引擎就行了，如果是手写的话，的确有点麻烦。其他基础不会有什么问题

是公司旧项目，纯原生mysql。。。我还是把php-ecc版本降低试试

**Comment by lpilp** [comment]
这样建议单独用PHP7或8 做一个国密的接口, 在5.6的项目中使用国密的时候都用调用本地接口的方式

**Comment by wzhih** [comment]
我已经成功移植到5.6了，谢谢

**Comment by xuening0610** [comment]
有没有大佬，解决下php5.4中只使用sm3,sm4，公司老项目，还是原生php，上面不舍得舍弃

**Comment by lpilp** [comment]
https://github.com/lizhichao/sm  sm3你用 这个， sm4用我的，你抠出来用，个别语法有问题的，你修改下，基本问题不大，

**Comment by Tang-hub** [comment]
> 我已经成功移植到5.6了，谢谢

您好，你这个是怎么弄的，我这边也是5.6的老项目，要用到这个根据 SM2 算法（Signature 的 algorithm 选择 SM3withSM2），签名报文

**Comment by wzhih** [comment]
> > 我已经成功移植到5.6了，谢谢
> 
> 您好，你这个是怎么弄的，我这边也是5.6的老项目，要用到这个根据 SM2 算法（Signature 的 algorithm 选择 SM3withSM2），签名报文

你试试我fork的： https://github.com/wzhih/guomi
其实就是里面语法改成5.6的而已

**Comment by Tang-hub** [comment]
> > > 我已经成功移植到5.6了，谢谢
> > 
> > 
> > 您好，你这个是怎么弄的，我这边也是5.6的老项目，要用到这个根据 SM2 算法（Signature 的 algorithm 选择 SM3withSM2），签名报文
> 
> 你试试我fork的： https://github.com/wzhih/guomi 其实就是里面语法改成5.6的而已

![image](https://user-images.githubusercontent.com/55779833/223964506-4448b86c-6e23-440b-acb2-cf5dd2b66934.png)
我这样安装报错，提示这样的

**Comment by Tang-hub** [comment]
> fork

这个有没有完整的安装包，直接引用就行，不用通过composer命令这种方式安装

**Comment by goyeee** [comment]
同php5.6版本 有可以协助对接java的加解密的吗 ？有偿。

**Comment by lpilp** [comment]
> 同php5.6版本 有可以协助对接java的加解密的吗 ？有偿。

你看项目的readme.md文件， PHP5.6 可以使用 本项目的简化版， https://github.com/lpilp/simplesm2 ，如有什么其他问题可以 看  compser.json里有我的微信号
