### ISSUE TITLE
对接招行需要使用SM3withSM2，sm2加密需要用sm2p256v1。

### ISSUE THREAD

**Issue by m1183909358** [lpilp/phpsm2sm3sm4#81]
![image](https://github.com/user-attachments/assets/f2b99f31-e1b8-4b65-a200-41f818de9321)
应如何解决求解

**Comment by m1183909358** [comment]
看过网上很多帖子，招行的签名只是 r+s的字符串组合需要进行一步转换SmSignFormatRS::asn1_to_rs($apiSign)为何还是失败，提示
![image](https://github.com/user-attachments/assets/4ceb4399-338e-40d4-8b9c-1b9bdeaee81d)

**Comment by m1183909358** [comment]
问题已解决，感觉大佬

**Comment by lpilp** [comment]
解决就好
