### ISSUE TITLE
为啥java那边提供给我的是更长的公钥

### ISSUE THREAD

**Issue by UKnowNothingJonSnow** [lpilp/phpsm2sm3sm4#84]
对方提供的公钥如下
MFkwEwYHKoZIzj0CAQYIKo*...*tPXA==
转hex之后如下
3059301306072a86*...*41a92f6bab5486e8d5eec92cbb8bf0ff4eb81b4f5c
是182个而不是130/128个hex字符
似乎他给的是标准pem的，有部分网站（https://the-x.cn/cryptography/Sm2.aspx）可以正常加密，而且一般的130/128HEX字符的，他也可以转成pem。
不懂啥原理

**Comment by lpilp** [comment]
```
3059301306072a8648ce3d020106082a811ccf5501822d034200049daf2f6ec33eb22e00b0635ff1f80caf1d57c32887e7f1bcf0f0628329b9df304cbee1f7e6bdfcda74ce4341a92f6bab5486e8d5eec92cbb8bf0ff4eb81b4f5c
```
这是密钥的简单的pkcs1的封装，用asn1  解开就行，建议先去学习下 asn1（预计15分钟） 封装就知道怎么回事了，

**Comment by UKnowNothingJonSnow** [comment]
哈哈，我昨晚研究到了，谢谢作者！
