### ISSUE TITLE
php sm2加密的数据 C#无法解密 

### ISSUE THREAD

**Issue by SunlessNight** [lpilp/phpsm2sm3sm4#86]
php 代码 :
$my_pubkey="044291b381a039a8d7d02d7272d2d7c78a30d33e3eeaa0b509bf77d2376582ab2d573730e6bfe9a53bad53f53ac1a85d9c11050931f04bc8b3afc04144d5a6f9be";
	    $my_prvkey="5aa03412c3051e1d4cf9d19cfbeeec70c28f388c9f82747cc912096c9cd44bea";
	    $input='{"phone":"123"}';
	    $sm2 = new RtSm2();
	    $m2EncryptData = $sm2 ->doEncrypt($input,$my_pubkey);
	    echo "公钥：".$my_pubkey;
	    echo "<br>";
	    echo "私钥：".$my_prvkey;
	    echo "<br>";
	    echo "加密串：".$m2EncryptData;
	    die;

公钥：044291b381a039a8d7d02d7272d2d7c78a30d33e3eeaa0b509bf77d2376582ab2d573730e6bfe9a53bad53f53ac1a85d9c11050931f04bc8b3afc04144d5a6f9be
私钥：5aa03412c3051e1d4cf9d19cfbeeec70c28f388c9f82747cc912096c9cd44bea
加密串：e27c3780e7069bda7082a23a489d77587ce309583ed99253f66e1d9833ed1a1d0b5ce86dc6714e9974cf258589139d7b1855e8c9fa2f2c1175ee123a95a23e9b008612c677981679474d079a9d572dd940e12547a6fb73454801a5507be81b04036c3c7340c9eb00636da5bab542eb

通过https://tool.hiofd.com/sm2-decrypt-online/ 这个解密工具 提示：error：sm2: decryption error 
<img width="912" alt="image" src="https://github.com/user-attachments/assets/e553412e-2a5b-4f5a-bece-ec2f2cbf9edb">

**Comment by SunlessNight** [comment]
求大佬帮忙解决啊

**Comment by SunlessNight** [comment]
看了以前的例子解决了 ， 得到的加密串前边补"04".加密传 就可以了

**Comment by lpilp** [comment]
> 看了以前的例子解决了 ， 得到的加密串前边补"04".加密传 就可以了

解决了就好，这个工具不错啊，支持各种格式，要是也能解决加04的就更好了，一般的常见的问题就是 ：asn1与c1c3c2顺序的问题，自动兼容就很好了
