### ISSUE TITLE
C# 支持吗 ，测试一直报错

### ISSUE THREAD

**Issue by wangzl2011** [lpilp/phpsm2sm3sm4#9]
C# 支持吗 ，测试一直报错

**Comment by lpilp** [comment]
php, java, js, python的问题我都可以给你看看， C#不熟悉，我搜了下，C#的在git也是有项目的， 你用的是哪个，搜索了下C#的， https://github.com/zxlwdgithub/guomi 这个看着应该没问题，你试试

**Comment by wangzl2011** [comment]
好的 我试试

**Comment by lpilp** [comment]
https://github.com/hz281529512/SecretTest 看了下，这个人封装的就比较好了
