### ISSUE TITLE
你好，请帮忙看看java中的这段代码如何在php中实现？我使用您的j代码貌似与这个不太匹配，我尝试翻写也失败了，还请帮忙，加v可有偿，ma_hua_teng1971

### ISSUE THREAD

**Issue by jiuerzhange** [lpilp/phpsm2sm3sm4#96]
public class Crypto {
    /**
     * 加密
     *
     * @param sourceData   原文
     * @param sm2PublicKey sm2公钥
     * @return 密文
     * @throws IOException 异常
     */
    public byte[] encrypt(byte[] sourceData, SM2PublicKey sm2PublicKey) throws IOException {
        ECPoint userKey = sm2PublicKey.getQ();
        AsymmetricCipherKeyPair keyPair = SM2Params.generators.generateKeyPair();
        ECPrivateKeyParameters ecpriv = (ECPrivateKeyParameters) keyPair.getPrivate();
        ECPublicKeyParameters ecpub = (ECPublicKeyParameters) keyPair.getPublic();
        BigInteger k = ecpriv.getD();
        ECPoint C1 = ecpub.getQ().normalize();
        BigInteger C1XCoord = C1.getXCoord().toBigInteger();
        BigInteger C1YCoord = C1.getYCoord().toBigInteger();
        ECPoint P2 = userKey.multiply(k).normalize();
        byte[] P2XBytes = BigIntegers.asUnsignedByteArray(32, P2.getXCoord().toBigInteger());
        byte[] P2YBytes = BigIntegers.asUnsignedByteArray(32, P2.getYCoord().toBigInteger());

        SM3Digest keySM3Engine = new SM3Digest();
        SM3Digest datSM3Engine = new SM3Digest();
        keySM3Engine.update(P2XBytes, 0, P2XBytes.length);
        keySM3Engine.update(P2YBytes, 0, P2YBytes.length);
        datSM3Engine.update(P2XBytes, 0, P2XBytes.length);
        int ct = 1;
        SM3Digest sm3keycur = new SM3Digest(keySM3Engine);
        sm3keycur.update((byte) (ct >> 24 & 255));
        sm3keycur.update((byte) (ct >> 16 & 255));
        sm3keycur.update((byte) (ct >> 8 & 255));
        sm3keycur.update((byte) (ct & 255));

        byte[] key = new byte[32];
        sm3keycur.doFinal(key, 0);
        byte keyOff = 0;
        ++ct;

        byte[] data = sourceData.clone();
        datSM3Engine.update(data, 0, data.length);

        for (int i = 0; i < data.length; ++i) {
            if (keyOff == key.length) {
                sm3keycur = new SM3Digest(keySM3Engine);
                sm3keycur.update((byte) (ct >> 24 & 255));
                sm3keycur.update((byte) (ct >> 16 & 255));
                sm3keycur.update((byte) (ct >> 8 & 255));
                sm3keycur.update((byte) (ct & 255));
                sm3keycur.doFinal(key, 0);
                keyOff = 0;
                ++ct;
            }

            byte var10002 = data[i];
            byte[] var10003 = key;
            byte var10006 = keyOff;
            keyOff = (byte) (var10006 + 1);
            data[i] = (byte) (var10002 ^ var10003[var10006]);
        }

        byte[] C2Hash = new byte[32];
        datSM3Engine.update(P2YBytes, 0, P2YBytes.length);
        datSM3Engine.doFinal(C2Hash, 0);
        keySM3Engine = new SM3Digest();
        datSM3Engine = new SM3Digest();
        keySM3Engine.update(P2XBytes, 0, P2XBytes.length);
        keySM3Engine.update(P2YBytes, 0, P2YBytes.length);
        datSM3Engine.update(P2XBytes, 0, P2XBytes.length);
        ct = 1;
        sm3keycur = new SM3Digest(keySM3Engine);
        sm3keycur.update((byte) (ct >> 24 & 255));
        sm3keycur.update((byte) (ct >> 16 & 255));
        sm3keycur.update((byte) (ct >> 8 & 255));
        sm3keycur.update((byte) (ct & 255));
        sm3keycur.doFinal(key, 0);
        keyOff = 0;
        ++ct;

        ASN1EncodableVector v = new ASN1EncodableVector();
        ASN1Integer xCoordinate = BigIntegers.formatXYRS(new ASN1Integer(C1XCoord));
        ASN1Integer yCoordinate = BigIntegers.formatXYRS(new ASN1Integer(C1YCoord));
        ASN1OctetString hashValue = new DEROctetString(C2Hash);
        ASN1OctetString cipherText = new DEROctetString(data);
        v.add(xCoordinate.formatToPositive(32));
        v.add(yCoordinate.formatToPositive(32));
        v.add(hashValue);
        v.add(cipherText);
        return new DERSequence(v).getEncoded();
    }

    /**
     * 解密
     *
     * @param encryptData   密文
     * @param sm2PrivateKey sm2私钥
     * @return 原文
     * @throws IOException 异常
     */
    public byte[] decrypt(byte[] encryptData, SM2PrivateKey sm2PrivateKey) throws Exception {
        BigInteger userD = sm2PrivateKey.getD();
        ASN1Sequence seq;
        try (ASN1InputStream asn1Is = new ASN1InputStream(encryptData)) {
            seq = (ASN1Sequence) asn1Is.readObject();
            Enumeration e = seq.getObjects();
            ASN1Integer xCoordinate = BigIntegers.formatXYRS(ASN1Integer.getInstance(e.nextElement()));
            ASN1Integer yCoordinate = BigIntegers.formatXYRS(ASN1Integer.getInstance(e.nextElement()));
//            ASN1OctetString hashValue = DEROctetString.getInstance(e.nextElement());
            ASN1OctetString cipherText = DEROctetString.getInstance(e.nextElement());
            ASN1OctetString hashValue = DEROctetString.getInstance(e.nextElement());
            BigInteger x = xCoordinate.getValue();
            BigInteger y = yCoordinate.getValue();
            byte[] encryptedBytes = hashValue.getOctets();
            byte[] hash = cipherText.getOctets();
            ECPoint c1 = SM2Params.sm2ParameterSpec.getCurve().createPoint(x, y);
            ECPoint P2 = c1.multiply(userD).normalize();
            byte[] P2XBytes = BigIntegers.asUnsignedByteArray(32, P2.getXCoord().toBigInteger());
            byte[] P2YBytes = BigIntegers.asUnsignedByteArray(32, P2.getYCoord().toBigInteger());
            SM3Digest keySM3Engine = new SM3Digest();
            SM3Digest datSM3Engine = new SM3Digest();
            keySM3Engine.update(P2XBytes, 0, P2XBytes.length);
            keySM3Engine.update(P2YBytes, 0, P2YBytes.length);
            datSM3Engine.update(P2XBytes, 0, P2XBytes.length);
            int ct = 1;
            SM3Digest sm3keycur = new SM3Digest(keySM3Engine);
            sm3keycur.update((byte) (ct >> 24 & 255));
            sm3keycur.update((byte) (ct >> 16 & 255));
            sm3keycur.update((byte) (ct >> 8 & 255));
            sm3keycur.update((byte) (ct & 255));
            byte[] key = new byte[32];
            sm3keycur.doFinal(key, 0);
            byte keyOff = 0;
            ++ct;
            byte[] decrypted = encryptedBytes.clone();

            for (int i = 0; i < decrypted.length; ++i) {
                if (keyOff == key.length) {
                    sm3keycur = new SM3Digest(keySM3Engine);
                    sm3keycur.update((byte) (ct >> 24 & 255));
                    sm3keycur.update((byte) (ct >> 16 & 255));
                    sm3keycur.update((byte) (ct >> 8 & 255));
                    sm3keycur.update((byte) (ct & 255));
                    sm3keycur.doFinal(key, 0);
                    keyOff = 0;
                    ++ct;
                }

                byte var10002 = decrypted[i];
                byte[] var10003 = key;
                byte var10006 = keyOff;
                keyOff = (byte) (var10006 + 1);
                decrypted[i] = (byte) (var10002 ^ var10003[var10006]);
            }

            datSM3Engine.update(decrypted, 0, decrypted.length);
            byte[] C2Hash = new byte[32];
            datSM3Engine.update(P2YBytes, 0, P2YBytes.length);
            datSM3Engine.doFinal(C2Hash, 0);
            keySM3Engine = new SM3Digest();
            datSM3Engine = new SM3Digest();
            keySM3Engine.update(P2XBytes, 0, P2XBytes.length);
            keySM3Engine.update(P2YBytes, 0, P2YBytes.length);
            datSM3Engine.update(P2XBytes, 0, P2XBytes.length);
            ct = 1;
            sm3keycur = new SM3Digest(keySM3Engine);
            sm3keycur.update((byte) (ct >> 24 & 255));
            sm3keycur.update((byte) (ct >> 16 & 255));
            sm3keycur.update((byte) (ct >> 8 & 255));
            sm3keycur.update((byte) (ct & 255));
            sm3keycur.doFinal(key, 0);
            keyOff = 0;
            ++ct;
            if (Arrays.equals(C2Hash, hash)) {
                return decrypted;
            } else {
                return null;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

**Comment by lpilp** [comment]
这个就是普通的sm2非对称的，只是生成的格式与我的不一样而已，我的格式是 c1c3c2,  这个java生成的是 asn1(c1x,c1y, c3,c2), 
解密的有一个热心网友提了PR， 在 rtsm2中有一个  doDecryptASN1 的可以解密，你再看看加密的时候生成 asn1就可以了，
PS： c1如何拆成c1x, c1y,  如果不带04的话， 对于hex格式的，是 后64个字节是c1y, 前64是c1x

**Comment by jiuerzhange** [comment]
> 这个就是普通的sm2非对称的，只是生成的格式与我的不一样而已，我的格式是 c1c3c2, 这个java生成的是 asn1(c1x,c1y, c3,c2), 解密的有一个热心网友提了PR， 在 rtsm2中有一个 doDecryptASN1 的可以解密，你再看看加密的时候生成 asn1就可以了， PS： c1如何拆成c1x, c1y, 如果不带04的话， 对于hex格式的，是 后64个字节是c1y, 前64是c1x

你好，感谢大佬指点，今天总算把c1c3c2的asn1编码搞完了，我能否提一个PR增加下asn1的相关加解密方法？

**Comment by lpilp** [comment]
可以

**Comment by jiuerzhange** [comment]
> 可以

能否加个v深入交流交流

**Comment by lpilp** [comment]
你的微信号是被腾讯给封了中，无此用户，可以加我 recent007
